version: "3.9"  # optional since v1.27.0
# ports and volumes use - host:container format
services:
  melijn-redis:
    image: redis:6.2.3
    container_name: "melijn-redis"
    restart: always
    ports:
      - 6379:6379
    command: redis-server --requirepass yourredispassword
  melijn-postgres:
    image: postgres:13-2
    container_name: "melijn-postgres"
    restart: always
    ports:
      - 5432:5432
    volumes: # Uncomment the one for your system if you want persistant storage
#      - /data/melijn-postgres:/var/lib/postgresql/data  # unix
#      - /c/Data/melijn-postgresql:/var/lib/postgresql/data # windows (also google how to enable /c/ sharing in docker desktop)
    env_file:
      - example-postgres.env