version: v1.0
name: Pull image on prod & shutdown bot
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
blocks:
  - name: Deploy
    task:
      secrets:
        - name: prod-deploy-details
      jobs:
        - name: Pull image & shutdown bot
          commands:
            - chmod 400 /home/semaphore/.ssh/id_rsa
            - ssh-keyscan -p ${PROD_SSH_PORT} -H ${PROD_SSH_HOST} >> /home/semaphore/.ssh/known_hosts
            - "ssh ${PROD_SSH_USER}@${PROD_SSH_HOST} -p ${PROD_SSH_PORT} ./melijn-bot/deploy.sh ${SEMAPHORE_GIT_SHA}"
            - curl -sL https://sentry.io/get-cli/ | bash
            - sentry-cli releases new -p melijn-bot ${SEMAPHORE_GIT_SHA}
            - sentry-cli repos list
            - sentry-cli releases set-commits ${SEMAPHORE_GIT_SHA} --commit "ToxicMushroom/Melijn@${SEMAPHORE_GIT_SHA}"
            - sentry-cli releases finalize ${SEMAPHORE_GIT_SHA}
            - sentry-cli releases deploys ${SEMAPHORE_GIT_SHA} new -e production