version: v1.0
name: Prod restart compose
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
blocks:
  - name: Deploy
    task:
      secrets:
        - name: prod-deploy-details
      jobs:
        - name: restart bot
          commands:
            - "chmod 400 /home/semaphore/.ssh/id_rsa"
            - "ssh-keyscan -p ${SSH_PORT} -H ${SSH_HOST} >> /home/semaphore/.ssh/known_hosts"
            - "ssh ${SSH_USER}@${SSH_HOST} -p ${SSH_PORT} sudo ./restart.sh"